version: '2'

services:

  test:
    image: php_test
    build: .
    ports:
      - "82:80"
    volumes:
      - ../school/:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:10.3
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always

volumes:
  mariadb: