 

name: Self Learning
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  sonarqubeAnalysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
